# Phân tích và hiển thị dữ liệu

In [5]:
v = list(range(1,6))
print(v)
print(2*v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [11]:
import numpy as np
v = np.arange(1,6)
print(v)
print(v*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [12]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [19]:
x = [60, 70, 80, 90]
print('len(x)=',len(x))
print('x[0]=',x[0])
print('x[1]=', x[1])
print('x[-1]=',x[-1])
print('x[1:3]=',x[1:3])

len(x)= 4
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]


In [26]:
from IPython.display import display
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print('c = ')
display(c)

c = 


array([ 4, 10, 18])

In [37]:
import numpy as np

a = np.zeros((2,2))
display(a)

b = np.ones((3,2))
display(b)

c = np.full((4,5),7)
display(c)

d = np.eye(4)
display(d)

e = np.random.random((2,2))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.9212202 , 0.69297611],
       [0.69820671, 0.24002304]])

In [48]:
import numpy as np
a = np.arange(15, dtype=float)
display(a)

a = a.reshape(3,5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [53]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

## Kết thúc