# Phân tích và hiển thị dữ liệu

In [1]:
v = list(range(1,6))
print(v)
print(2*v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np
v = np.arange(1,6)
print(v)
print(v*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [3]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [4]:
x = [60, 70, 80, 90]
print('len(x)=',len(x))
print('x[0]=',x[0])
print('x[1]=', x[1])
print('x[-1]=',x[-1])
print('x[1:3]=',x[1:3])

len(x)= 4
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]


In [5]:
from IPython.display import display
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print('c = ')
display(c)

c = 


array([ 4, 10, 18])

In [6]:
import numpy as np

a = np.zeros((2,2))
display(a)

b = np.ones((3,2))
display(b)

c = np.full((4,5),7)
display(c)

d = np.eye(4)
display(d)

e = np.random.random((2,2))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.15808478, 0.97112079],
       [0.99372919, 0.36234922]])

In [7]:
import numpy as np
a = np.arange(15, dtype=float)
display(a)

a = a.reshape(3,5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

(4, 5)

2

dtype('int64')

In [10]:
a = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23]
])
display(a)
display(a.shape)
display(a.ndim)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

(3, 4)

2

In [11]:
a = np.arange(1, 10).reshape(3,3)
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
display(a[2])
display(a[2].shape)

display(a[2,:])
display(a[2,:].shape)

display(a[2:,:])
display(a[2:,:].shape)

array([7, 8, 9])

(3,)

array([7, 8, 9])

(3,)

array([[7, 8, 9]])

(1, 3)

## Pandas

In [13]:
from IPython.display import display
import pandas as pd
a = pd.DataFrame({
        'a': [4,5,6],
        'b': [7,8,9],
        'c': [10,11,12],
    }, index = [1,2,3])
display(a)
display(a.loc[1])

b = pd.DataFrame([
    {'a':4,'b':7,'c':10},
    {'a':5,'b':8,'c':11},
    {'a':6,'b':9,'c':12},
])
display(b)
display(b.loc[1])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

a     4
b     7
c    10
Name: 1, dtype: int64

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [14]:
display(type(a))

pandas.core.frame.DataFrame

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s = pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001', periods = 6)
display(dates)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df = pd.DataFrame(np.random.randn(6,4), columns=['A','B','C','D'], index = dates)
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

A         B         C         D
2018-10-01  0.947524 -1.494152 -1.380455  0.600651
2018-10-02  0.365780  0.567198 -0.547348  0.107879
2018-10-03  0.841310 -0.315282  1.573174 -0.566982
2018-10-04 -0.299715 -1.340216  1.560972  0.541990
2018-10-05 -1.285053  0.378443 -0.425832  0.283318
2018-10-06  0.964866  0.465060 -0.367518  0.085228

A    0.841310
B   -0.315282
C    1.573174
D   -0.566982
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01   -1.494152
2018-10-02    0.567198
2018-10-03   -0.315282
2018-10-04   -1.340216
2018-10-05    0.378443
2018-10-06    0.465060
Freq: D, Name: B, dtype: float64

In [17]:
df = pd.DataFrame(np.random.randn(3,5), columns=list('ABCDE'), index=['student 1','student 2', 'student 3'])
df

A         B         C         D         E
student 1  0.330481  0.327885 -0.632326  0.424950 -0.821069
student 2 -0.061919 -0.316385 -0.624545 -0.451415  0.012392
student 3  0.002371 -1.292099  0.893304  0.397342 -0.650247

In [19]:
df2 = pd.DataFrame({ 
    'A' : 1.,
    'B' : pd.Timestamp('20181001'),
    'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
    'D' : np.array([3] * 4,dtype='int32'),
    'E' : pd.Categorical(["test","train","test","train"]),
    'F' : 'foo' 
})
display(df2)

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [21]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [26]:
import pandas as pd
from IPython.display import display

# Create a DataFrame to store transactions
columns = ['Date', 'Description', 'Amount']
ledger = pd.DataFrame(columns=columns)
# display(ledger)

# Init a DataFrame to store transactions
def init_ledger():
    return pd.DataFrame(columns=columns)

# Function to add a transaction
def add_transaction(date, description, amount):
    global ledger
    new_transaction = pd.DataFrame([[date, description, amount]], columns=columns)
    ledger = pd.concat([ledger, new_transaction], ignore_index=True)

# Function to view the ledger
def view_ledger():
    display(ledger)

# Function to get the current balance
def get_balance():
    return ledger['Amount'].sum()

ledger = init_ledger()

# Adding sample transactions
add_transaction('2023-11-01', 'Income', 1000)
add_transaction('2023-11-02', 'Groceries', -200)
add_transaction('2023-11-03', 'Utilities', -100)

# Viewing the ledger
view_ledger()

# Checking the current balance
print("Current Balance:", get_balance())

Date Description Amount
0  2023-11-01      Income   1000
1  2023-11-02   Groceries   -200
2  2023-11-03   Utilities   -100

Current Balance: 700


## Kết thúc